# Generated by Django 2.2.2 on 2019-07-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
